module.exports = {
  USER_TYPES: {
    USER: 'User',
    MANAGER: 'Manager',
    ADMIN: 'Admin'
  },
  USER_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
  },
  PERMISSION_TYPES: {
    EDIT: 'EDIT',
    ROTATE: 'ROTATE',
    DISABLE: 'DISABLE',
    ENABLE: 'ENABLE',
    DELETE: 'DELETE',
    ALL_ACESS: 'ALL ACESS'
  },
  STATUS: {
    ENABLE: 'ENABLE',
    DISABLE: 'DISABLE',
    PENDING: 'PENDING',
    DEL_FILE: 'DELETE FILE'
  },
  EVENT_TYPE: {
    CREATE_KEY: 'CREATE KEY',
    UPDATE_KEY: 'UPDATE KEY',
    DEL_KEY: 'DELETE KEY',
    ROTATE_KEY: 'ROTATE KEY',
    UPLOAD_FILE: 'UPLOAD FILE',
    DOWNLOAD_FILE: 'DOWNLOAD FILE',
    ENCRYPT_FILE: 'ENCRYPT FILE'
  }
}